### PR TITLE
fixes #102 and #104

### LINKED ISSUE #102: StackOverflowError on any DB connection/creation on latest and 0.4.5
```julia
using SQLite
db = SQLite.DB()
````

```
LoadError: StackOverflowError:
while loading In[1], in expression starting on line 2

 in call at C:\Users\amellnik\.julia\v0.4\SQLite\src\SQLite.jl:48 (repeats 2 times)
```

I'm using the most recent tagged release of Compat (0.7.18) which seems like it might be related -- I assume this was introduced with https://github.com/JuliaDB/SQLite.jl/commit/198468bba9618bfa0b952d408c22001fbc35926f.

### PR DESCRIPTION
**Pull request by felipenoris**
For a pass on all tests, the following PRs should also be merged:

https://github.com/JuliaDB/DataStreams.jl/pull/9
https://github.com/JuliaDB/CSV.jl/pull/22

### CODE REVIEW

**Comment by felipenoris** [comment]
Actually there's a fail on test only on 0.5. I'll take a look.
```
@test size(ds) == (11,1)
```

**Comment by quinnj** [comment]
Typically that's an artifact of a previous test run's not getting cleaned up properly (because a test table gets created, but not dropped)

**Comment by felipenoris** [comment]
Indeed... After some cleanup I get some internal errors. Maybe related to C API. I'll take a look.

**Comment by felipenoris** [comment]
The error occurs on this line of code :
```julia
r = SQLite.query(db, SQLite.@sr_str("SELECT LastName FROM Employee WHERE BirthDate REGEXP '^\\d{4}-08'"))
```

Results in
```julia
ERROR: LoadError: MethodError: Cannot `convert` an object of type Array{Any,1} to an object of type LambdaInfo
```

**Comment by felipenoris** [comment]
@quinnj , I squashed the commits. I guess I'm done.

**Comment by quinnj** [comment]
Thanks @felipenoris!

**Pull request merged**
