### PR TITLE
Handle NullableArrays with missing, undefined vals

### PR DESCRIPTION
**Pull request by amellnik**
Don't attempt to access the value without first making sure the value is
not null.  Fixes https://github.com/JuliaDB/SQLite.jl/issues/88.

### CODE REVIEW

**Comment by nalimilan** [comment]
I think you could write this even more concisely using `get`. Another advantage is that you don't need to play with the internals of the `NullableArray`:
```julia
function getbind!(dt::NullableVector,row,col,stmt)
        @inbounds val = get(dt[row], NULL)
        SQLite.bind!(stmt, col, val)
end
```

One would have to check that the performance is as good as your version, though.

**Comment by Sean1708** [comment]
Thanks for the effort @amellnik, could you put a test in about this and then it should be good to merge.

Alternatively (because I know our test file is a bit messy at the moment) could you give me a small example which fails on master but passes on this branch and I'll put the test in myself.

**Comment by amellnik** [comment]
Thanks @Sean1708, here's a short example which passes on this commit and should fail on the master (although I unfortunately don't have time to check atm).  

```julia
arr = Array(Any,2) 
arr[1] = 1 #Now an array with the second value undefined
nv = NullableArrays.NullableArray(arr, [false, true])
schema = DataStreams.Data.Schema(["nv"], [Int64])
d = NullableArrays.NullableVector([nv])
dt = DataStreams.Data.Table(schema, d)
db = SQLite.DB("temp.sqlite")
SQLite.drop!(db, "temp", ifexists=true)
sink = SQLite.Sink(dt, db, "temp")
Data.stream!(dt, sink);
````

**Comment by amellnik** [comment]
Just to follow up, I eventually found time and the latest commit includes tests for this.

**Comment by Sean1708** [comment]
@amellnik I'm so sorry, I'd completely forgotten about this. Looks good though, thanks.

**Comment by quinnj** [comment]
Yes, thanks for this @amellnik. Sorry for being slow on the responses lately; moving into a new house has been more taxing that I ever imagined.

**Comment by amellnik** [comment]
No problem!  I know moving is always a hassle -- good luck.

**Pull request merged**
