### PR TITLE
Changing query result type

### PR DESCRIPTION
**Pull request by yjk21**
Hello,
thanks for this great library.
I found it to be convenient to have arrays returned by query() to be typed for primitive data types.
I added a few lines to achieve this.
Cheers!
yj

### CODE REVIEW

**Comment by quinnj** [comment]
The key problem here is dealing with potential NULL values, which precludes strongly typing a result column. It may make sense to have some kind of special method or mode or something where we can strongly type the result columns when it's guaranteed to not have nulls, but in the general case, we need to consider their potential existence.

That and there's a lot of weird whitespace/indentation changes in this PR :)

**Comment by yjk21** [comment]
Hi,
oh I see. Didn't think about that :)

About missing values, there is this blog post:
http://www.johnmyleswhite.com/notebook/2014/11/29/whats-wrong-with-statistics-in-julia/
John refers to strategies that R and pandas dataframes adopt to represent missing values.
Do you think that would be something worth looking into?

Just noticed the white space thing.. not sure what went wrong there.

**Comment by Sean1708** [comment]
We've also got to bear in mind that SQLite is not statically typed, just because a column says it contains integers doesn't mean every row will be an integer.

**Comment by felipenoris** [comment]
I would say the core of this discussion is to understand what ```t = sqlite3_column_type(stmt.handle,i-1)``` does. Does it check the table schema? If that´s the case, as pointed out by @Sean1708, that´s a pain: you cannot guarantee that a column has only the data type defined on the table schema.

For instance, if you declare a column as ```NUMERIC```, RSQLite (the equivalent package on R) infers the type of the column by assessing the type of the element on the first row. If the value on the first line reads ```10```, and you got ```12.2``` on the second line, the value of the second line will be converted to integer, returning ```12```. If you declare a column as ```REAL```, RSQLite returns always a floating point value on the resulting Data Frame.
If you have to check the entire result set to decide on a specific data type to return, you´ll kill performance.

If returning arrays as ```Any[]```, which I understand that is the current solution, doesn´t kill performance, maybe the current solution is ideal, and the user of the package should convert to appropriate types. However, I would consider this package to provide strong typed results as an optional feature (for those who don´t create poorly designed databases). In this case, maybe you should consider returning result sets as a DataFrame instance (```DataFrames.jl```), which would provide a solution to null values.

**Comment by quinnj** [comment]
Good summary @felipenoris. Some know of my hate for DataFrames.jl, but I guess not all; I'll forgive you this time for mentioning it :)
No, but seriously, returning `Any[]` is currently the best way to get the results in a generic way while still getting typed values (as opposed to all strings). We should definitely explore another query method that returns a more tightly typed result.

**Comment by felipenoris** [comment]
@quinnj, I share with you that hatred in my heart about DataFrames... and I also hate null values! :+1:

**Comment by quinnj** [comment]
I think we have a pretty good story here with the entire DataStreams ecosystem

**Pull request closed without merging**
