### PR TITLE
close ephemeral Stmt when executing string query.

### PR DESCRIPTION
**Pull request by getzdan**
another little fix (got a few of these).
IMO finalizing handles early should be encouraged since there is no guarantee regarding GC schedule.

### CODE REVIEW

**Comment by Sean1708** [comment]
Weirdly `Pkg.test` considers these to be passing tests, but if you look [here](https://travis-ci.org/JuliaDB/SQLite.jl/jobs/93646708#L145) you can see that you're getting a lot of errors from calling `_close` multiple times. This should be fixed by calling `finalize` on the statement, instead of `_close` directly.

**Comment by getzdan** [comment]
ah, ok. that in fact was my next little fix: make the \_close/finalize idempotent, in the sense that they wouldn't mind being called multiple times. seems like a good quality for close (it's a check if `x.handle` is `C_NULL` / `NULL`

**Comment by getzdan** [comment]
sorry for the piecemeal fixes, but it usually is for the best, especially when just familiarizing with the package.

**Comment by Sean1708** [comment]
I still think it would be best practice to use `finalize` instead of `_close`. If we imagine for a second that `_close` can be called twice without any consequences, what would happen is:

1. Create `stmt`.
2. Call `execute!` on `stmt`.
3. Explicitly call `_close` on `stmt`.
4. `stmt` goes out of scope.
5. At some future point `_close` is called as part of the finalizer.

If you change `_close(stmt)` to `finalize(stmt)`, then you'll get the following:

1. Create `stmt`.
2. Call `execute!` on `stmt`.
3. Call `finalize` on `stmt` which implicitly calls `_close`  _and prevents the finalizer being called when `stmt` goes out of scope_.
4. `stmt` goes out of scope.

If you're creating a lot of statements then preventing that second `_close` call could have a surprising performance impact.

Further to this if we have to add a second finalizer to `Stmt` at some point in the future (for whatever reason) then `finalize` would future-proof our code for us.

> seems like a good quality for close (it's a check if `x.handle` is `C_NULL` / `NULL`

[We used to do this](https://github.com/JuliaDB/SQLite.jl/blob/a4108ff5cf3943b5a03fba9932c9f5f03065d9e4/src/SQLite.jl#L105), so it's a regression that our tests didn't pick up on.

> sorry for the piecemeal fixes

Don't worry about it, it makes discussions like this easier.

**Comment by getzdan** [comment]
`finalize` contacts the GC and it has few guarantees (could simply sleep on it and keep the handle allocated on the `sqlite` library side). Best to keep things in the module and let finalize do its thing when it does.

**Comment by getzdan** [comment]
according to docs `finalize` calls registered functions immediately. so it might be OK. but the ephemeral Stmt should be finalized.

**Comment by Sean1708** [comment]
I agree that the ephemeral Stmt should be finalised, but I think `finalize` is the more correct way to do it. You can see from the [source](https://github.com/JuliaLang/julia/blob/124f71c27fcf1a5576c2e79f1291a6b990bb54c4/src/gc.c#L424) that `finalize` does run the finalizers immediately, so (unless I'm missing something) the only difference between the two is that `finalize` runs all finalizers and prevents them from being run twice.

**Pull request closed without merging**
